name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: my-backend:latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK for backend build
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Build backend
      - name: Build Spring Boot app
        run: mvn clean package -DskipTests

      # Build frontend
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Security scanner 1: Trivy (Docker image scan)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          image-ref: $DOCKER_IMAGE
          format: 'table'
          exit-code: '1'        # Fail workflow if vulnerabilities found
          severity: 'HIGH,CRITICAL'

      # Security scanner 2: Gitleaks (detect secrets)
      - name: Scan repository for secrets with Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: gitleaks.toml
          verbose: true
          exit-code: 1          # Fail workflow if leaks found

      # Optional: Kubernetes manifest linting (kube-linter)
      - name: Install kube-linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/stackrox/kube-linter/main/install.sh | sh
          sudo mv kube-linter /usr/local/bin/kube-linter

      - name: Lint Kubernetes manifests
        run: kube-linter lint k8s-manifests/
